declare const PROTON_CONFIG = "PROTON_CONFIG";
declare const PROTON_SERVER = "PROTON_SERVER";
declare const PROTON_LOGGER = "PROTON_LOGGER";
declare const CONTROLLER_ROUTES = "CONTROLLER_ROUTES";
declare const DEPENDENCIES = "DEPENDENCIES";
export { PROTON_CONFIG, PROTON_SERVER, PROTON_LOGGER, CONTROLLER_ROUTES, DEPENDENCIES };
