const PROTON_CONFIG = 'PROTON_CONFIG';
const PROTON_SERVER = 'PROTON_SERVER';
const PROTON_LOGGER = 'PROTON_LOGGER';
const CONTROLLER_ROUTES = 'CONTROLLER_ROUTES';
const DEPENDENCIES = 'DEPENDENCIES';

export {
  PROTON_CONFIG,
  PROTON_SERVER,
  PROTON_LOGGER,
  CONTROLLER_ROUTES,
  DEPENDENCIES
};
